<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE root [    
    <!ELEMENT MusicDB (Album+)>
    <!ELEMENT Album (AlbumTitle,AlbumArtist,Genre,Publisher,Year,AlbumPrice,Songs)>
    <!ELEMENT AlbumTitle (#PCDATA)>
    <!ELEMENT AlbumArtist (#PCDATA)>
    <!ELEMENT Genre (#PCDATA)>
    <!ELEMENT Publisher (#PCDATA)>
    <!ELEMENT Year (#PCDATA)>
    <!ELEMENT AlbumPrice (#PCDATA)>
    <!ELEMENT Songs (Song+)>
    <!ELEMENT Song (SongTitle,SongArtist,SongAlbum,SongPrice)>
    <!ELEMENT SongTitle (#PCDATA)>
    <!ELEMENT SongArtist (#PCDATA)>
    <!ELEMENT SongAlbum (#PCDATA)>
    <!ELEMENT SongPrice (#PCDATA)>
]>

<MusicDB>
<Album>
	<AlbumTitle>Watermark</AlbumTitle>
	<AlbumArtist>Enya</AlbumArtist>
	<Genre>New Age</Genre>
	<Publisher>Warner Music UK Ltd</Publisher>
	<Year>1988</Year>
	<AlbumPrice>16.99</AlbumPrice>
	
	
	
	
	
	
	
	
	
	
	
	
	<Songs><Song>
		<SongTitle>Watermark</SongTitle>
		<SongArtist>Enya</SongArtist>
		<SongAlbum>Watermark</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Cursum Perfico</SongTitle>
		<SongArtist>Enya</SongArtist>
		<SongAlbum>Watermark</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>On Your Shore</SongTitle>
		<SongArtist>Enya</SongArtist>
		<SongAlbum>Watermark</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Storms In Africa</SongTitle>
		<SongArtist>Enya</SongArtist>
		<SongAlbum>Watermark</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Exile</SongTitle>
		<SongArtist>Enya</SongArtist>
		<SongAlbum>Watermark</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Miss Clare Remembers</SongTitle>
		<SongArtist>Enya</SongArtist>
		<SongAlbum>Watermark</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Orinoco Flow</SongTitle>
		<SongArtist>Enya</SongArtist>
		<SongAlbum>Watermark</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Evening Falls...</SongTitle>
		<SongArtist>Enya</SongArtist>
		<SongAlbum>Watermark</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>River</SongTitle>
		<SongArtist>Enya</SongArtist>
		<SongAlbum>Watermark</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Longships</SongTitle>
		<SongArtist>Enya</SongArtist>
		<SongAlbum>Watermark</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Na Laetha Geal M'oige</SongTitle>
		<SongArtist>Enya</SongArtist>
		<SongAlbum>Watermark</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Storms in Africa, Pt. 2</SongTitle>
		<SongArtist>Enya</SongArtist>
		<SongAlbum>Watermark</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song></Songs></Album>
<Album>
	<AlbumTitle>December</AlbumTitle>
	<AlbumArtist>George Winston</AlbumArtist>
	<Genre>Chritmas</Genre>
	<Publisher>Dancing Cat Productions</Publisher>
	<Year>1982</Year>
	<AlbumPrice>16.99</AlbumPrice>
	
	
	
	
	
	
	
	
	
	
	
	
	<Songs><Song>
		<SongTitle>Thanksgiving</SongTitle>
		<SongArtist>George Winston</SongArtist>
		<SongAlbum>December</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Jesus, Jesus, Rest Your Head</SongTitle>
		<SongArtist>George Winston</SongArtist>
		<SongAlbum>December</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Joy</SongTitle>
		<SongArtist>George Winston</SongArtist>
		<SongAlbum>December</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Prelude</SongTitle>
		<SongArtist>George Winston</SongArtist>
		<SongAlbum>December</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Carol of the Bells</SongTitle>
		<SongArtist>George Winston</SongArtist>
		<SongAlbum>December</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Night, Pt. 1: Snow</SongTitle>
		<SongArtist>George Winston</SongArtist>
		<SongAlbum>December</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Night, Pt. 2: Midnight</SongTitle>
		<SongArtist>George Winston</SongArtist>
		<SongAlbum>December</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Night, Pt. 3: Minstrels</SongTitle>
		<SongArtist>George Winston</SongArtist>
		<SongAlbum>December</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Variations on the Kanon by Pachelbel</SongTitle>
		<SongArtist>George Winston</SongArtist>
		<SongAlbum>December</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Holly and the Ivy</SongTitle>
		<SongArtist>George Winston</SongArtist>
		<SongAlbum>December</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Some Children See Him</SongTitle>
		<SongArtist>George Winston</SongArtist>
		<SongAlbum>December</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Peace</SongTitle>
		<SongArtist>George Winston</SongArtist>
		<SongAlbum>December</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song></Songs></Album>
<Album>
	<AlbumTitle>Piano Stories</AlbumTitle>
	<AlbumArtist>Joe Hisaishi</AlbumArtist>
	<Genre>Pop</Genre>
	<Publisher>Wonder City Inc.</Publisher>
	<Year>2000</Year>
	<AlbumPrice>10.49</AlbumPrice>
	
	
	
	
	
	
	
	
	
	
	
	<Songs><Song>
		<SongTitle>Prologue:A Summer's Day</SongTitle>
		<SongArtist>Joe Hisaishi</SongArtist>
		<SongAlbum>Piano Stories</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Resphoina</SongTitle>
		<SongArtist>Joe Hisaishi</SongArtist>
		<SongAlbum>Piano Stories</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>W Nocturne</SongTitle>
		<SongArtist>Joe Hisaishi</SongArtist>
		<SongAlbum>Piano Stories</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Lady of Spring</SongTitle>
		<SongArtist>Joe Hisaishi</SongArtist>
		<SongAlbum>Piano Stories</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Wind Forest,The</SongTitle>
		<SongArtist>Joe Hisaishi</SongArtist>
		<SongAlbum>Piano Stories</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Dreamy Child</SongTitle>
		<SongArtist>Joe Hisaishi</SongArtist>
		<SongAlbum>Piano Stories</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Green Requiem</SongTitle>
		<SongArtist>Joe Hisaishi</SongArtist>
		<SongAlbum>Piano Stories</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Twilight Shore,The</SongTitle>
		<SongArtist>Joe Hisaishi</SongArtist>
		<SongAlbum>Piano Stories</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Innocent</SongTitle>
		<SongArtist>Joe Hisaishi</SongArtist>
		<SongAlbum>Piano Stories</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Fantasia(For Nausica)</SongTitle>
		<SongArtist>Joe Hisaishi</SongArtist>
		<SongAlbum>Piano Stories</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Epilogue:A Summer's Day</SongTitle>
		<SongArtist>Joe Hisaishi</SongArtist>
		<SongAlbum>Piano Stories</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song></Songs></Album>
<Album>
	<AlbumTitle>Schindler's List</AlbumTitle>
	<AlbumArtist>John Williams</AlbumArtist>
	<Genre>Soundtrack</Genre>
	<Publisher>Geffen Records</Publisher>
	<Year>1994</Year>
	<AlbumPrice>16.99</AlbumPrice>
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	<Songs><Song>
		<SongTitle>Theme From Schindler's List</SongTitle>
		<SongArtist>John Williams</SongArtist>
		<SongAlbum>Schindler's List</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Jewish Town (krakow Ghetto - Winter '41)</SongTitle>
		<SongArtist>John Williams</SongArtist>
		<SongAlbum>Schindler's List</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Immolation (with Our Lives, We Give Life)</SongTitle>
		<SongArtist>John Williams</SongArtist>
		<SongAlbum>Schindler's List</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Remembrances</SongTitle>
		<SongArtist>John Williams</SongArtist>
		<SongAlbum>Schindler's List</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Schindler's Workforce</SongTitle>
		<SongArtist>John Williams</SongArtist>
		<SongAlbum>Schindler's List</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Oyf'n Pripetshok And Nacht Aktion</SongTitle>
		<SongArtist>John Williams</SongArtist>
		<SongAlbum>Schindler's List</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>I Could Have Done More</SongTitle>
		<SongArtist>John Williams</SongArtist>
		<SongAlbum>Schindler's List</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Auschwitz - Birkenau</SongTitle>
		<SongArtist>John Williams</SongArtist>
		<SongAlbum>Schindler's List</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Stolen Memories</SongTitle>
		<SongArtist>John Williams</SongArtist>
		<SongAlbum>Schindler's List</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Making The List</SongTitle>
		<SongArtist>John Williams</SongArtist>
		<SongAlbum>Schindler's List</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Give Me Your Names</SongTitle>
		<SongArtist>John Williams</SongArtist>
		<SongAlbum>Schindler's List</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Yeroushalaim Chel Zahav (jerusalem Of Gold)</SongTitle>
		<SongArtist>John Williams</SongArtist>
		<SongAlbum>Schindler's List</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Remembrances (with Itzhak Perlman)</SongTitle>
		<SongArtist>John Williams</SongArtist>
		<SongAlbum>Schindler's List</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song><Song>
		<SongTitle>Theme From Schindler's List (reprise)</SongTitle>
		<SongArtist>John Williams</SongArtist>
		<SongAlbum>Schindler's List</SongAlbum>
		<SongPrice>1.69</SongPrice>
	</Song></Songs></Album>
</MusicDB>